### ISSUE TITLE
An error is coming with the PUPI_DM plugin

### ISSUE THREAD

**Issue by arjunsuresh** [pupi1985/q2a-pupi-fns#1]
On enabling this plugin from the admin page the site is not working and the below server error can be seen. Not sure how they are related though. 
```
PHP Fatal error:  Uncaught Error: Class 'PUPI_DM_CkeditorInjector' not found in 
/var/www/html/qa/qa-plugin/pupi-dm/PUPI_DM_Editor.php:36\nStack trace:\n#0 
/var/www/html/qa/qa-include/qa-base.php(924): PUPI_DM_Editor->load_module()\n#1 
/var/www/html/qa/qa-include/qa-base.php(948): qa_load_module()\n#2 /var/www/html/qa/qa-include/app/options.php(538): 
qa_load_all_modules_with()\n#3 /var/www/html/qa/qa-include/app/options.php(86): qa_default_option()\n#4 /var/www/html/qa/qa-include/qa-base.php(1863): qa_get_options()\n#5 
/var/www/html/qa/qa-plugin/q2a-pupi-fns/qa-plugin.php(49): qa_opt()\n#6 /var/www/html/qa/qa-include/Q2A/Plugin/PluginManager.php(91): 
require_once('/var/www/html/q...')\n#7 /var/www/html/qa/qa-include/Q2A/Plugin/PluginManager.php(114): 
Q2A_Plugin_PluginManager->loadPlugins()\n#8 /var/www/html/qa/qa-include/qa-base.php(405): Q2A_Plugin_PluginManager->loadPluginsAfterDbInit()\n#9 /var/www/html/qa/qa-include/qa-page.php(36): 
qa_initialize_postdb_plugins()\n#10 /var/www/html/qa/qa-include/qa-index.php(189): require('/var/www/htm in 
 /var/www/html/qa/qa-plugin/pupi-dm/PUPI_DM_Editor.php on line 36
```

**Comment by pupi1985** [comment]
Thank you for reporting this. This is a fix that is needed in the PUPI DM plugin. I fixed it a few days ago but I just haven't had time to publish it (updating the documentation and distributing the update). I've just done so. Take a look at the new update and let me know if it doesn't work.

**Comment by arjunsuresh** [comment]
Thanks a lot @pupi1985 . It did fix that issue but I think a similar error is coming from the Circles plugin. 
```
PHP Fatal error:  Uncaught Error: Class 'ARSU_CIRC_ActionButtonsLayerHelper' not found in /var/www/html/qa/qa-include/qa-base.php:921\nStack trace:\n#0 /var/www/html/qa/qa-include/qa-base.php(948): qa_load_module()\n#1 /var/www/html/qa/qa-include/app/options.php(538): qa_load_all_modules_with()\n#2 /var/www/html/qa/qa-include/app/options.php(86): qa_default_option()\n#3 /var/www/html/qa/qa-include/qa-base.php(1863): qa_get_options()\n#4 /var/www/html/qa/qa-plugin/q2a-pupi-fns/qa-plugin.php(49): qa_opt()\n#5 /var/www/html/qa/qa-include/Q2A/Plugin/PluginManager.php(91): require_once('/var/www/html/q...')
```

**Comment by pupi1985** [comment]
Check this new release and let me know if the issue persists: https://github.com/pupi1985/q2a-pupi-fns/releases/tag/v1.0.1

**Comment by arjunsuresh** [comment]
Thank you Pupi. Now the issue is resolved :+1:

**Comment by pupi1985** [comment]
Please, re-download the version 1.0.1 again I just made a minor but relevant speed change :man_facepalming:

**Comment by arjunsuresh** [comment]
Thank you :) Now its much faster. Just need to put the icon properly in our theme. 
https://aptitude.gateoverflow.in/activity
